### ISSUE TITLE
Crash in AppNavigator

### ISSUE THREAD

**Issue by robertlevonyan** [terrakok/Cicerone#167]
The app is crashing with error `IllegalStateException: FragmentManager has been destroyed`

Full crash log:

```
Fatal Exception: java.lang.IllegalStateException: FragmentManager has been destroyed
       at androidx.fragment.app.FragmentManager.B(FragmentManager.java:16)
       at androidx.fragment.app.FragmentManager.generateOpsForPendingActions(FragmentManager.java)
       at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:2)
       at com.github.terrakok.cicerone.androidx.AppNavigator.applyCommandsSync(AppNavigator.java:2)
       at com.github.terrakok.cicerone.androidx.AppNavigator$applyCommands$1.run(AppNavigator.java:2)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7562)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by robertlevonyan** [comment]
Also I'm receiving this issue:

```
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1)
       at androidx.fragment.app.FragmentManager.popBackStack(FragmentManager.java:8)
       at com.github.terrakok.cicerone.androidx.AppNavigator.replace(AppNavigator.java:8)
       at com.github.terrakok.cicerone.androidx.AppNavigator.applyCommand(AppNavigator.java:8)
       at com.github.terrakok.cicerone.androidx.AppNavigator.applyCommandsSync(AppNavigator.java:8)
       at com.github.terrakok.cicerone.androidx.AppNavigator$applyCommands$1.run(AppNavigator.java:8)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

and this:

```
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1)
       at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:4)
       at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:1)
       at com.github.terrakok.cicerone.androidx.AppNavigator.commitNewFragmentScreen(AppNavigator.java:16)
       at com.github.terrakok.cicerone.androidx.AppNavigator.replace(AppNavigator.java:9)
       at com.github.terrakok.cicerone.androidx.AppNavigator.applyCommandsSync(AppNavigator.java:8)
       at com.github.terrakok.cicerone.androidx.AppNavigator$applyCommands$1.run(AppNavigator.java:8)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7814)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```
