### ISSUE TITLE
Crash in version 7.1

### ISSUE THREAD

**Issue by robertlevonyan** [terrakok/Cicerone#168]
```
java.lang.IllegalStateException: FragmentManager is already executing transactions
        at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:1636)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1695)
        at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:564)
        at com.github.terrakok.cicerone.androidx.AppNavigator.applyCommands(AppNavigator.kt:25)
```

**Comment by robertlevonyan** [comment]
`view?.post { navigator.applyCommands(arrayOf(Replace(screen = screen))) }` is fixing the problem, but I think this should be done inside the lib

**Comment by GreyLabsDev** [comment]
Or maybe Handler(Looper.getMainLooper()) with handler.post {navigator.applyCommands(arrayOf(Replace(screen = screen)))}, for more save using this method without taking view reference
