### ISSUE TITLE
Crash in version 7.1

### ISSUE THREAD

**Issue by robertlevonyan** [terrakok/Cicerone#173]
```
atal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1)
       at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:4)
       at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:1)
       at com.github.terrakok.cicerone.androidx.AppNavigator.commitNewFragmentScreen(AppNavigator.java:9)
       at com.github.terrakok.cicerone.androidx.AppNavigator.replace(AppNavigator.java:5)
       at com.github.terrakok.cicerone.androidx.AppNavigator.applyCommands(AppNavigator.java:7)
       at com.robertlevonyan.testy.ui.main.MainFragment.onItemSelected$lambda-10$lambda-9(MainFragment.java:53)
       at androidx.camera.camera2.internal.Camera2CameraControlImpl$CameraCaptureCallbackSet$$InternalSyntheticLambda$9$e5350c1b11be8bdf6a3182cb638daed28e6e5f26d5bae717586c49615918254f$0.run$bridge(Camera2CameraControlImpl.java:53)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8059)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

**Comment by umbrellait-Zafar-Abdulloev** [comment]
I have the same issue 
In the Activity i set a navigator in:     
override fun onResumeFragments() {
        super.onResumeFragments()
        navigatorHolder.setNavigator(navigator)
}

Note: I have multiple navigators for instance: Activity->AuthFlow->SignInFragment (There are 2 navigators, in the Activity and in the FlowFragment)

But in case with flow fragments we don't have such method. I'm calling setNavigator method on resume with flow fragments. Maybe that's why i'm getting such error, but there is no other options

**Comment by lyrjie** [comment]
@terrakok , hello
Is there a current maintainer for the library? There haven't been any work in last two years and critical issues like this one are left without a comment for more than a year
Could you please mark the repository as unsupported / deprecated, if it's an orphan

**Comment by terrakok** [comment]
Hello! I'm here and there are no contributions for two reasons:
 1) the reported one is not a library issue but a FragmentManager behavior which was discussed lots of times.
 2) library is stable enough at the moment. and since Compose for Android is recommended way to make applications, I don't have ideas to develop the library
 
If you have ideas PRs are more than welcome!

Regarding the issue: https://github.com/terrakok/Cicerone/issues/160

@VitalyPeryatin may add a comment here, I guess.

**Comment by lyrjie** [comment]
This current issue is reproducible on 7.1
As far as I understand the [comment](https://github.com/terrakok/Cicerone/issues/160#issuecomment-881835269), it assumes the Router is cleared in onPause; which is an assumation on the user's app architecture. Meanwhile, I've seen some developers inject Router directly into, for example, presenter, meaning there's no onPause handling. It's, of course, for you to decide whether to support such a usage or not

Thanks for the prompt answer!

**Comment by Zhuinden** [comment]
> This current issue is reproducible on 7.1 As far as I understand the [comment](https://github.com/terrakok/Cicerone/issues/160#issuecomment-881835269), it assumes the Router is cleared in onPause; which is an assumation on the user's app architecture. Meanwhile, I've seen some developers inject Router directly into, for example, presenter, meaning there's no onPause handling. It's, of course, for you to decide whether to support such a usage or not
> 
> Thanks for the prompt answer!

That's a bug on library user's part, they should observe `ProcessLifecycleOwner` to know attach/detach of the app itself if they don't control the NavigationHolder otherwise from Fragment lifecycle.
