### ISSUE TITLE
java.lang.IllegalStateException:  ... declared target fragment FilterFragment{9cee0b7} that does not belong to this FragmentManager!

### ISSUE THREAD

**Issue by zezekalo** [terrakok/Cicerone#78]
I've got an exception when trying set Target Fragment (Android 7.0, Samsung J-330), support version  - 27.1.0

```
BRAND_SELECTION_FRAGMENT -> {
                    val fragment = BrandSelectionFragment.newInstance(data as ArrayList<StationNetwork>)
                    fragment.setTargetFragment(filterFragment, BRAND_SELECTION_REQUEST_CODE)
                    fragment
                }
```

```
java.lang.IllegalStateException: Fragment BrandSelectionFragment{99d4bb6 #1 id=0x7f0a00c8} declared target fragment FilterFragment{9cee0b7} that does not belong to this FragmentManager!
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1354)
        at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1188)
        at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1071)
        at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:115)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2379)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2337)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2244)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:702)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```
is this still Android bug and what could be the steps to fix it?

**Comment by terrakok** [comment]
I think that this two fragments placed in different fragment managers
